baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'ГипсБуд'

sass:
  style: compact # possible values: nested expanded compact compressed

google_analytics_id: UA-175458432-1

plugins:
  - jekyll-environment-variables
  - jekyll-sitemap
  - jekyll-seo-tag
